AppBundle\Domain\Entity\User:
  type: entity
  table: user
  schema: notes
  repositoryClass: AppBundle\Infrastructure\Repository\UserRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
  oneToMany:
    notes:
      targetEntity: AppBundle\Domain\Entity\Note
      mappedBy: user